spring.application.name=sistema-crm
spring.datasource.url=jdbc:mysql://root:XZARjNYUZAhnIdwGwfpsDcABMmigmKcf@hopper.proxy.rlwy.net:47001/railway
spring.datasource.username=root
spring.datasource.password=XZARjNYUZAhnIdwGwfpsDcABMmigmKcf
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect