spring.application.name=sistema-crm
# URL de R2DBC (fijate en el prefijo r2dbc:pool:postgres://)
spring.r2dbc.url=r2dbc:pool:postgres://postgres:pTPxHMiBPoYSVPoPdWZIogsPGIlutOaP@postgres.railway.internal:5432/railway
spring.r2dbc.username=postgres
spring.r2dbc.password=pTPxHMiBPoYSVPoPdWZIogsPGIlutOaP

# Esto crea las tablas automaticamente si no existen (util en desarrollo)
spring.sql.init.mode=always