spring.application.name=sistema-crm
#spring.datasource.url=jdbc:mysql://root:diVIjNVxbQmgIyzwmzKxtbTvNScPyCKO@interchange.proxy.rlwy.net:28627/railway
#spring.datasource.username=root
#spring.datasource.password=diVIjNVxbQmgIyzwmzKxtbTvNScPyCKO
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect